inherit_from: .rubocop_todo.yml

require:
  - rubocop-rails

# 対象外
AllCops:
  Exclude:
    - "vendor/**/*"
    - "bin/**"
    - "db/schema.rb"
    - "node_modules/**/*"
    - "tmp/**/*"
    - "lib/**/*"
  DisplayCopNames: true
  TargetRubyVersion: 2.6

# trueかfalseを設定しないと警告が出る
Style/HashEachMethods:
  Enabled: true
Style/HashTransformKeys:
  Enabled: true
Style/HashTransformValues:
  Enabled: true

##################### Style ##################################

# 日本語のコメントを許可する
Style/AsciiComments:
  Enabled: false

# ドキュメントの無いpublic classを許可する
Style/Documentation:
  Enabled: false

# !! のイディオムを許可
Style/DoubleNegation:
  Enabled: false

#文字列をfreezeするか
Style/FrozenStringLiteralComment:
  Enabled: false

# selfが無くても良い時に省略するか。model内において、ローカル変数とメソッド呼び出しの区別をつけた方が分かりやすい場合が多い
Style/RedundantSelf:
  Enabled: false

##################### Lint ##################################

##################### Metrics ##################################

# 変数の代入(A)、メソッドの呼び出し等(B)、条件分岐(C)から算出される複雑度
Metrics/AbcSize:
  Max: 30

# 循環的複雑度 ≒ 分岐の数
Metrics/CyclomaticComplexity:
  Max: 10

# 1行の文字数
Metrics/LineLength:
  Max: 160
  Exclude:
    - "db/migrate/*.rb"

# メソッドの行数
Metrics/MethodLength:
  Max: 20
  Exclude:
    - "db/migrate/*.rb"

# このアプリ特有の除外項目
Lint/SuppressedException:
  Exclude:
    - 'config/unicorn/production.rb'

Metrics/BlockLength:
  Max: 163

Metrics/ClassLength:
  Max: 119

Rails/BulkChangeTable:
  Exclude:
    - 'db/migrate/20210819142244_add_column_to_users.rb'

Rails/FilePath:
  Exclude:
    - 'app/uploaders/image_uploader.rb'
    - 'config/environments/development.rb'
    - 'config/schedule.rb'
    - 'db/seeds/production.rb'
    - 'spec/rails_helper.rb'
    - 'spec/system/conditions_spec.rb'

Rails/InverseOf:
  Exclude:
    - 'app/models/user.rb'

Style/GlobalVars:
  Exclude:
    - 'config/unicorn/production.rb'
